language: ruby

rvm:
  - 2.5.1

before_install:
 # https://github.com/travis-ci/travis-ci/issues/8978#issuecomment-377680126
 - gem install bundler

script:
- bundle exec rubocop
- bundle exec rake spec:ci
