- name: Set hostname
  hostname:
    name: lovetrack-button
  tags: hostname,dns

- name: Set hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 lovetrack-button"
  tags: hostname,dns

- name: Use http redirector for apt
  replace:
    dest: /etc/apt/sources.list
    regexp: 'ftp.us'
    replace: 'httpredir'
  tags: apt,localization

- name: Install software
  apt:
    update_cache: yes
    name:
      - aptitude # required for upgrade mode 'full'
      - tmux
      - htop
      - vim
    state: present
  tags: apt

- name: Upgrade all software
  apt:
    upgrade: full
  tags: apt

- name: Copy the public key of the user who is running ansible to the remote machine
  authorized_key:
    user: chip
    key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_rsa.pub') }}"
  tags: ssh

- name: Start the ssh service
  systemd:
    name: ssh
    state: started
    enabled: true
  tags: ssh

- name: No stupid login message
  file:
    path:  /home/chip/.hushlogin
    state: touch
    owner: chip
    group: chip
    mode:  "0755"
  tags: user

- name: Set keyboard layout to DE
  copy:
    src: keyboard
    dest: /etc/default/keyboard
    owner: root
    group: root
    mode: 0644
  tags: localization

- name: Add the user 'chip' to the list of sudoers
  copy:
    src: sudoers
    dest: /etc/sudoers.d/chip
    owner: root
    group: root
    mode: "0640"
  tags: user,security
