- name: Install prerequisite software
  apt:
    update_cache: yes
    name:
      - python3
      - python3-dev
      - python3-pip
#      - flex
#      - git
#      - build-essential
#      - bison
    state: present
  tags: apt,python,button

- name: Install prerequisite python packages
  pip:
    requirements: requirements.txt
    executable: pip3
  tags: python,button

- name: Copy LoveTrack button script
  template:
    src: lovetrack-button.j2
    dest: "/usr/local/sbin/lovetrack-button"
    mode: "0755"
  tags: button

- name: Create LoveTrack button systemd service config
  copy:
    src: "lovetrack-button.service"
    dest: "/etc/systemd/system/"
    mode: "0664"
  tags: systemd,button

- name: Start the LoveTrack service
  systemd:
    name: lovetrack-button
    state: started
    enabled: true
  tags: systemd,button
