- name: Set hostname
  hostname:
    name: lovetrack-button
  tags: hostname,dns

- name: Set hostname in /etc/hosts
  lineinfile:
    dest: /etc/hosts
    line: "127.0.0.1 lovetrack-button"
  tags: hostname,dns

- name: Install python
  apt:
    update_cache: yes
    name:
      - python3
      - python3-pip
#      - python3-dev
#      - flex
#      - git
#      - build-essential
#      - bison
    state: present
  tags: apt,python,button

- name: Copy python requirements file
  copy:
    src: requirements.txt
    dest: /opt/lovetrack-button/
    mode: "0755"
  tags: python,button

- name: Install prerequisite python packages
  pip:
    requirements: /opt/lovetrack-button/requirements.txt
    executable: pip3
  tags: python,button

- name: Remove old LoveTrack button script
  file:
    src: /usr/local/sbin/lovetrack-button
    state: absent
  tags: button

- name: Copy LoveTrack button script
  template:
    src: lovetrack-button.j2
    dest: /opt/lovetrack-button/bin/lovetrack-button
    mode: "0755"
  tags: button

- name: Create LoveTrack button systemd service config
  copy:
    src: lovetrack-button.service
    dest: /etc/systemd/system/
    mode: "0664"
  tags: systemd,button

- name: Start the LoveTrack service
  systemd:
    name: lovetrack-button
    daemon-reload: true
    state: restarted
    enabled: true
  tags: systemd,button
